config/routes.rb
Rails.application.routes.draw do
  resources :comandos
 
  root 'pages#home'
  get 'home' => 'pages#home'
  get 'login' => 'pages#login'
  post 'login' => 'pages#accesologin'
  get 'registrate' => 'usuarios#new'
  post 'usuarios' => 'usuarios#create'
  patch 'usuarios/:id' => 'usuarios#update'
  put 'usuarios/:id' => 'usuarios#update'
  get 'salir' => 'pages#salir'
  get 'delComando/:id'=> 'comandos#destroy', as: :delComando
  get 'delSnapshot/:id'=> 'snapshots#destroy', as: :delSnapshot
  get 'delOrden/:id'=> 'ordens#destroy', as: :delOrden
  get 'maquinaVirtual/:id'=> 'maquina_virtuals#show', as: :maquina_virtual
  get 'delMaquinaVirtual/:key/:so/:host/:id'=> 'maquina_virtuals#destroy', as: :delMaquinaVirtual
  get 'maquinas/:id'=> 'maquinas#show', as: :maquina
  get 'delMaquina/:id'=> 'maquinas#destroy', as: :delMaquina
  get 'delUsuario/:id'=> 'usuarios#destroy', as: :delUsuario
  get 'perfil/:id'=> 'usuarios#show', as: :perfil
  get 'usuarios/:id' => 'usuarios#show', as: :usuario
  get 'newKey/:id'=> 'usuarios#newKey', as: :newKey
  get 'key/:id' => 'ordens#existe_user'
  get 'so' => 'ordens#SO'
  get 'existeMaquina/:key/:so/:host' => 'ordens#existeMaquina'
  get 'crearMaquina/:key/:so/:host' => 'maquinas#crearMaquina'
  get 'ordenes/:key/:so/:host' => 'ordens#ordenes'
  get 'delOrdenClient/:key/:so/:host/:id'=> 'ordens#delete'
  get 'actualizarMV/:id'=> 'maquina_virtuals#actualizarMV', as: :actualizarMV
  get 'vnc/:id' => 'maquina_virtuals#vnc', as: :vnc
  get 'mv/:key/:so/:host/:hypervisor/:nombre/:ruta/:memoriaTotal/:memoria/:estado/:rutaHDD/:sizeTotalMV/:sizeOcupadoMV/:sizeTotalMaquina/:snapshots' => 'maquina_virtuals#mv', as: :mv
  get 'getlistmvs/:key/:so/:host' => 'comandos#getlistmvs'
  get 'accion/:comando/:id/:valor' => 'maquina_virtuals#accion', as: :accion
  get 'changevnc/:id/:ipvnc/:portvnc'=> 'maquina_virtuals#changevnc'
  get 'listaComandos'=> 'comandos#listaComandos'
  get '*path' => redirect('/')
end

app/models/maquina.rb
class Maquina < ActiveRecord::Base
  belongs_to :usuario
  has_many :ordens, :dependent => :destroy
  has_many :maquina_virtuals, :dependent => :destroy
  has_many :comandos, :dependent => :destroy
  
  validates :nombre ,:SO , presence: true
  
  validates :SO, length: { in: 3..255 , message: "debe tener entre 3 y 255 caracteres"}
end

app/controllers/maquinas_controller.rb
class MaquinasController < ApplicationController
  before_action :set_maquina, only: [:show,:destroy]
  before_action :require_login
 skip_before_action :require_login, only: [:crearMaquina]
 
   def require_login
     current_user
    unless @current_user!=nil
      redirect_to root_path
    end
  end
  
  def show
    current_user
  end
  
  def crearMaquina
    current_user
    user = Usuario.find_by(auth: params[:key])
   if user!=nil
     maquina=user.maquinas.find_by(SO: params[:so],nombre: params[:host])
     
     if maquina==nil
       maquina = user.maquinas.build
       maquina.SO=params[:so]
       maquina.nombre=params[:host]
       maquina.save
       
     end
   end
   redirect_to root_path
  end

  # DELETE /maquinas/1
  # DELETE /maquinas/1.json
  def destroy
    current_user
    @maquina.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maquina
      @maquina = Maquina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maquina_params
      params.require(:maquina).permit(:nombre, :SO)
    end
end

app/helpers/maquinas_helper.rb
module MaquinasHelper
end

app/views/maquinas/show.html.erb
<head>
		<title>HyperZen | <%=@maquina.nombre%> | <%=@maquina.SO%></title>
		<% user @current_user %>
		<meta http-equiv="refresh" content="30">
	</head>
<body>
	<div id="page-wrapper">
		<div class="main-page">
				<div class="elements">	
				<div class="elements  row">
					<div class="col-md-11 profile widget-shadow chat-mdl-grid" style="width: 100%;">
						<h4 class="title3" ><%=@maquina.nombre%> | <%=@maquina.SO%></h4>
						<div class="scrollbar scrollbar1" >
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Hypervisor</th>
										<th>Nombre</th>
										<th>RAM</th>
										<th>HDD</th>
										<th>Estado</th>
										<th colspan="1"></th>
										<th colspan="1"></th>
									</tr>
								</thead>
								<tbody>
									<% MaquinaVirtual.all.where(:maquina_id=>@maquina.id).each do |mv|%>
									<tr style="border-bottom: 1px gainsboro solid;">
										<td><%= mv.hypervisor%></td>
										<td><%= mv.nombre%></td>
										<td><%= mv.opciones.split("ram=")[1].split(";")[0]%> MB</td>
										<td><%= mv.opciones.split("sizeOcupadoMV=")[1].split(";")[0]%> MB / <%= mv.opciones.split("sizeTotalMV=")[1].split(";")[0]%> MB</td>
										<td><%= mv.estado%></td>
										<td><%=link_to maquina_virtual_path(mv) do%><i class="fa fa-file-o" style="color:#e94e02;"></i> <%end%></td>
										<td><%=link_to actualizarMV_path(mv) do%><i class="fa fa-refresh" style="color:#e94e02;"></i>  <%end%></td>
									</tr>
									<%end%>
								</tbody>
							</table>
						</div>
					</div>
					
					
					
					
	
					
					</div>
					<div class="clearfix"> </div>
					
				</div>
			</div>
			</div>
</body>