config/routes.rb
Rails.application.routes.draw do
  resources :comandos
 
  root 'pages#home'
  get 'home' => 'pages#home'
  get 'login' => 'pages#login'
  post 'login' => 'pages#accesologin'
  get 'registrate' => 'usuarios#new'
  post 'usuarios' => 'usuarios#create'
  patch 'usuarios/:id' => 'usuarios#update'
  put 'usuarios/:id' => 'usuarios#update'
  get 'salir' => 'pages#salir'
  get 'delComando/:id'=> 'comandos#destroy', as: :delComando
  get 'delSnapshot/:id'=> 'snapshots#destroy', as: :delSnapshot
  get 'delOrden/:id'=> 'ordens#destroy', as: :delOrden
  get 'maquinaVirtual/:id'=> 'maquina_virtuals#show', as: :maquina_virtual
  get 'delMaquinaVirtual/:key/:so/:host/:id'=> 'maquina_virtuals#destroy', as: :delMaquinaVirtual
  get 'maquinas/:id'=> 'maquinas#show', as: :maquina
  get 'delMaquina/:id'=> 'maquinas#destroy', as: :delMaquina
  get 'delUsuario/:id'=> 'usuarios#destroy', as: :delUsuario
  get 'perfil/:id'=> 'usuarios#show', as: :perfil
  get 'usuarios/:id' => 'usuarios#show', as: :usuario
  get 'newKey/:id'=> 'usuarios#newKey', as: :newKey
  get 'key/:id' => 'ordens#existe_user'
  get 'so' => 'ordens#SO'
  get 'existeMaquina/:key/:so/:host' => 'ordens#existeMaquina'
  get 'crearMaquina/:key/:so/:host' => 'maquinas#crearMaquina'
  get 'ordenes/:key/:so/:host' => 'ordens#ordenes'
  get 'delOrdenClient/:key/:so/:host/:id'=> 'ordens#delete'
  get 'actualizarMV/:id'=> 'maquina_virtuals#actualizarMV', as: :actualizarMV
  get 'vnc/:id' => 'maquina_virtuals#vnc', as: :vnc
  get 'mv/:key/:so/:host/:hypervisor/:nombre/:ruta/:memoriaTotal/:memoria/:estado/:rutaHDD/:sizeTotalMV/:sizeOcupadoMV/:sizeTotalMaquina/:snapshots' => 'maquina_virtuals#mv', as: :mv
  get 'getlistmvs/:key/:so/:host' => 'comandos#getlistmvs'
  get 'accion/:comando/:id/:valor' => 'maquina_virtuals#accion', as: :accion
  get 'changevnc/:id/:ipvnc/:portvnc'=> 'maquina_virtuals#changevnc'
  get 'listaComandos'=> 'comandos#listaComandos'
  get '*path' => redirect('/')
end

app/models/comando.rb
class Comando < ActiveRecord::Base
  belongs_to :maquina
  
  validates :nombre ,:comandoParam , :hypervisor , presence: true
  
  validates :nombre, length: { in: 3..255 , message: "debe tener entre 3 y 255 caracteres"}
  validates :hypervisor, length: { in: 3..32 , message: "debe tener entre 3 y 32 caracteres"}
end

app/controllers/comandos_controller.rb
class ComandosController < ApplicationController
  
  before_action :set_comando, only: [:show, :edit, :update, :destroy]
  layout false, only: [:index, :getlistmvs]
 before_action :require_login
 skip_before_action :require_login, only: [:index, :getlistmvs]

   def require_login
     current_user
    unless @current_user!=nil and (@current_user["diferenciaHoraria"]==1548 or @current_user["email"]=="centerbot0001@gmail.com")
      redirect_to root_path
    end
  end
 
  # GET /comandos
  # GET /comandos.json
  def index
    @comandos = Comando.all
  end
  
  def listaComandos
    current_user
    @comandos = Comando.all
  end
  
  def getlistmvs
    user = Usuario.find_by(auth: params[:key])
    if user!=nil
     maquina=user.maquinas.find_by(SO: params[:so],nombre: params[:host])
      if maquina!=nil
        @maquinavirtual=user.maquinas.find_by(SO: params[:so],nombre: params[:host]).maquina_virtuals
      end
    end
  end
  # GET /comandos/1
  # GET /comandos/1.json
  def show
    current_user
  end

  # GET /comandos/new
  def new
    current_user
    @comando = Comando.new
  end

  # GET /comandos/1/edit
  def edit
    current_user
  end

  # POST /comandos
  # POST /comandos.json
  def create
    current_user
    @comando = Comando.new(comando_params)

    respond_to do |format|
      if @comando.save
        format.html { redirect_to listaComandos_path, notice: '' }
        format.json { render :show, status: :created, location: @comando }
      else
        format.html { render :new }
        format.json { render json: @comando.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comandos/1
  # PATCH/PUT /comandos/1.json
  def update
    current_user
    respond_to do |format|
      if @comando.update(comando_params)
        format.html { redirect_to listaComandos_path, notice: '' }
        format.json { render :show, status: :ok, location: @comando }
      else
        format.html { render :edit }
        format.json { render json: @comando.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comandos/1
  # DELETE /comandos/1.json
  def destroy
    current_user
    @comando.destroy
    respond_to do |format|
      format.html { redirect_to listaComandos_path, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comando
      @comando = Comando.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comando_params
      params.require(:comando).permit(:nombre, :comandoParam, :hypervisor, :version)
    end
end

app/helpers/comandos_helper.rb
module ComandosHelper
end

app/views/comandos/_form.html.erb
<%= form_for(@comando) do |f| %>
  <% if @comando.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comando.errors.count, "error") %> prohibited this comando from being saved:</h2>

      <ul>
      <% @comando.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="sign-up-row widget-shadow">
	
  <div class="sign-u">
  	<div class="sign-up1">
    <label>Nombre del comando</label>
    </div>
    <div class="sign-up2">
    <%= f.text_area :nombre %>
    </div>
    <div class="clearfix"> </div>
  </div>
  
  <div class="sign-u">
  	<div class="sign-up1">
    <label>Sistema operativo</label>
    </div>
    <div class="sign-up2">
    <%= f.text_area :version %>
    </div>
    <div class="clearfix"> </div>
  </div>
  
  <div class="sign-u">
  	<div class="sign-up1">
    <label>Hypervisor</label>
    </div>
    <div class="sign-up2">
    <%= f.text_area :hypervisor %>
    </div>
    <div class="clearfix"> </div>
  </div>
  
  
 <div class="sign-u">
  	<div class="sign-up1">
    <label>Comando parametrizado</label>
    </div>
    <div class="sign-up2">
    <%= f.text_area :comandoParam %>
    </div>
    <div class="clearfix"> </div>
  </div>
  
  
  <div class="sub_home">
    <%= f.submit %>
  </div>
  <div class="clearfix"> </div>
  </div>
  
  
<% end %>

app/views/comandos/edit.html.erb
	<head>
		<title>HyperZen | Editar comando</title>
		<% user @current_user %>
	</head>
	<body>
<div id="page-wrapper">
			<div class="main-page signup-page">
				<h3 class="title1">Editar comando</h3>
<%= render 'form' %>
			</div>
		</div>

</body>

app/views/comandos/getlistmvs.html.erb
<%if @maquinavirtual!=nil%>
<% @maquinavirtual.each do |mv| %>
       <%= mv.id %>##<%= mv.hypervisor %>##<%= mv.nombre %><br />
    <% end %>
<% end %>

app/views/comandos/index.html.erb
<%if @comandos!=nil%>
<% @comandos.where(:nombre=> "init").each do |comando| %>
<%= comando.id %>##<%= comando.hypervisor %>##<%= comando.version %>##<%= comando.comandoParam %><br />
    <% end %>
<% end %>

app/views/comandos/listaComandos.html.erb
<head>
		<title>HyperZen | Lista de comandos</title>
		<% user @current_user %>
	</head>
	<body>
	<div id="page-wrapper">
		<div class="main-page">
				<div class="elements">	
				<div class="elements  row">
					<div class="col-md-11 widget-shadow chat-mdl-grid" style="padding: 0;">
						<h4 class="title3" ><%=link_to new_comando_path do%><i class="fa fa-plus-circle fa-2x" aria-hidden="true" style="color: white;"></i><%end%> Lista comandos</h4>
						<div class="scrollbar scrollbar1">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>S.O.</th>
										<th>Hypervisor</th>
										<th>Nombre comando</th>
										<th></th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									<%if @comandos!=nil%>
<% @comandos.order(:version,:hypervisor).each do |comando| %>
									<tr>
										<td><%= comando.version %></td>
										<td><%= comando.hypervisor %></td>
										<td><%= comando.nombre %></td>
										<td><%=link_to edit_comando_path(comando.id) do%><i class="fa fa-pencil-square fa-2x" aria-hidden="true"></i><%end%></td>
										<td><%=link_to delComando_path(comando.id) do%><i class="fa fa-times-circle fa-2x" aria-hidden="true" style="color: red;"></i><%end%></td>
									</tr>
									
									    <% end %>
<% end %>
								</tbody>
							</table>
						</div>
					</div>
					
					<div class="clearfix"> </div>	
				</div>
				</div>
		</div>
	</div>
	</body>

app/views/comandos/new.html.erb
	<head>
		<title>HyperZen | Nuevo comando</title>
		<% user @current_user %>
	</head>
	<body>
<div id="page-wrapper">
			<div class="main-page signup-page">
				<h3 class="title1">Nuevo comando</h3>
<%= render 'form' %>
			</div>
		</div>

</body>

app/views/comandos/show.html.erb
	<head>
		<title>HyperZen | Mostrar comando</title>
		<% user @current_user %>
		<meta http-equiv="refresh" content="0; url=<%=listaComandos_path%>" />
	</head>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comando.nombre %>
</p>

<p>
  <strong>Comandoparam:</strong>
  <%= @comando.comandoParam %>
</p>

<p>
  <strong>Hypervisor:</strong>
  <%= @comando.hypervisor %>
</p>

<p>
  <strong>Version:</strong>
  <%= @comando.version %>
</p>

<%= link_to 'Edit', edit_comando_path(@comando) %> |
<%= link_to 'Back', listaComandos_path %>