config/routes.rb
Rails.application.routes.draw do
  resources :comandos
 
  root 'pages#home'
  get 'home' => 'pages#home'
  get 'login' => 'pages#login'
  post 'login' => 'pages#accesologin'
  get 'registrate' => 'usuarios#new'
  post 'usuarios' => 'usuarios#create'
  patch 'usuarios/:id' => 'usuarios#update'
  put 'usuarios/:id' => 'usuarios#update'
  get 'salir' => 'pages#salir'
  get 'delComando/:id'=> 'comandos#destroy', as: :delComando
  get 'delSnapshot/:id'=> 'snapshots#destroy', as: :delSnapshot
  get 'delOrden/:id'=> 'ordens#destroy', as: :delOrden
  get 'maquinaVirtual/:id'=> 'maquina_virtuals#show', as: :maquina_virtual
  get 'delMaquinaVirtual/:key/:so/:host/:id'=> 'maquina_virtuals#destroy', as: :delMaquinaVirtual
  get 'maquinas/:id'=> 'maquinas#show', as: :maquina
  get 'delMaquina/:id'=> 'maquinas#destroy', as: :delMaquina
  get 'delUsuario/:id'=> 'usuarios#destroy', as: :delUsuario
  get 'perfil/:id'=> 'usuarios#show', as: :perfil
  get 'usuarios/:id' => 'usuarios#show', as: :usuario
  get 'newKey/:id'=> 'usuarios#newKey', as: :newKey
  get 'key/:id' => 'ordens#existe_user'
  get 'so' => 'ordens#SO'
  get 'existeMaquina/:key/:so/:host' => 'ordens#existeMaquina'
  get 'crearMaquina/:key/:so/:host' => 'maquinas#crearMaquina'
  get 'ordenes/:key/:so/:host' => 'ordens#ordenes'
  get 'delOrdenClient/:key/:so/:host/:id'=> 'ordens#delete'
  get 'actualizarMV/:id'=> 'maquina_virtuals#actualizarMV', as: :actualizarMV
  get 'vnc/:id' => 'maquina_virtuals#vnc', as: :vnc
  get 'mv/:key/:so/:host/:hypervisor/:nombre/:ruta/:memoriaTotal/:memoria/:estado/:rutaHDD/:sizeTotalMV/:sizeOcupadoMV/:sizeTotalMaquina/:snapshots' => 'maquina_virtuals#mv', as: :mv
  get 'getlistmvs/:key/:so/:host' => 'comandos#getlistmvs'
  get 'accion/:comando/:id/:valor' => 'maquina_virtuals#accion', as: :accion
  get 'changevnc/:id/:ipvnc/:portvnc'=> 'maquina_virtuals#changevnc'
  get 'listaComandos'=> 'comandos#listaComandos'
  get '*path' => redirect('/')
end

app/views/pages/home.html.erb
	<head>
		<title>HyperZen | Inicio</title>
		<% user @current_user %>
		<meta http-equiv="refresh" content="20">
	</head>
	<body>
<div id="page-wrapper">
			<div class="main-page">
				<h3 class="title1">¡Bienvenid@ a Hyperzen!</h3>
				<div class="blank-page widget-shadow scroll" id="style-2 div1">
					<p>Esta es una pagina que te <strong>permitirá controlar tus maquinas virtuales a distancia</strong>. Para ello tendrá que realizar <strong>3 sencillos pasos</strong>:
					</p>
					<br />
					<div  id="accordion" role="tablist" aria-multiselectable="true">
				  <div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingOne">
					  <h4 class="panel-title">
						<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
						  1. Resgistrese.
						</a>
					  </h4>
					</div>
					<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
					  <div class="panel-body">
						Tan solo tendrá que <%=link_to registrate_path do%>registrarse<%end%>.
					  </div>
					</div>
				  </div>
				  <div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingTwo">
					  <h4 class="panel-title">
						<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
							2. Descargue y ponga en marcha nuestra aplicación cliente.
						</a>
					  </h4>
					</div>
					<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
					  <div class="panel-body">
						1 - Descargue e instale el <a href="https://www.ruby-lang.org/es/downloads/">software de ruby</a>.</br>

						2 - Abra una consola de comandos y ejecute &quot;<i>gem install qtbindings</i>&quot;.</br>

						3 - Descargue la aplicacion cliente:</br>

						<a href="../Hyperzen_client_Windows.exe"><button>Windows(.exe)</button></a><a href="../Hyperzen_client_Windows(source).rb"><button>Windows(source)</button></a><a href="../Hyperzen_client_Deb-based(GUI).rb"><button>Linux(deb-based)</button></a><a href="../Hyperzen_client_Rpm-based(GUI).rb"><button>Linux(rpm-based)</button></a><a href="../Hyperzen_client_Mac.rb"><button>Mac OS X</button></a></br>

						4 - Abrir una consola de comandos y ejecutar&nbsp;&quot;<i>ruby &lt;ruta de la aplicaci&oacute;n cliente&gt;.rb</i>&quot;. Excepto si se ha descargado el ejecutable.</br>

						5 - Una vez abierta la aplicaci&oacute;n cliente, entra en tu perfil en esta p&aacute;gina y clica en Secret Key. Esos caracteres alfanum&eacute;ricos copialos y pegalos en la aplicaci&oacute;n cliente. Pulsa en Enviar y listo. En breve podr&aacute;s gestionar tus m&aacute;quinas virtuales desde la pagina.
					  </div>
					</div>
				  </div>
				  <div class="panel panel-default">
					<div class="panel-heading" role="tab" id="headingThree">
					  <h4 class="panel-title">
						<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
							3. Inicia sesión en la aplicación cliente y en la web.
						</a>
					  </h4>
					</div>
					<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
					  <div class="panel-body">
						Iniciando sesión en la aplicación cliente y en la web ya podrás acceder a tus maquinas virtuales desde la web.
						</div>
					</div>
				  </div>
				  
				</div>
				</div>
			</div>
			</body>
		

app/views/pages/login.html.erb
	<head>
		<title>HyperZen | Login</title>
		<% user @current_user %>
	</head>
	<body>
<div id="page-wrapper">
			<div class="main-page login-page ">
				<h3 class="title1">¡Bienvenid@ a Hyperzen!</h3>
				<div class="widget-shadow">
					<div class="login-top">
						<h4>¿Todavía no eres miembro? <%=link_to registrate_path do%>Registrate »<%end%> </h4>
						<font style="color: red"><%=@error%></font>
					</div>
					<div class="login-body">
						<%= form_for(@user, url: login_path) do |f| %>
							<input type="text" class="user" name="usuario[emailLogin]" placeholder="Email" required="">
							<input type="password" name="usuario[passwordLogin]" class="lock" placeholder="Password">
							<%=f.submit "Entrar"%>
							<div class="forgot-grid">
								<div class="forgot">
									<a href="#">¿Olvidaste la contraseña?</a>
								</div>
								<div class="clearfix"> </div>
							</div>
						<%end%>
					</div>
				</div>
			</div>
			</body>