config/routes.rb
Rails.application.routes.draw do
  resources :comandos
 
  root 'pages#home'
  get 'home' => 'pages#home'
  get 'login' => 'pages#login'
  post 'login' => 'pages#accesologin'
  get 'registrate' => 'usuarios#new'
  post 'usuarios' => 'usuarios#create'
  patch 'usuarios/:id' => 'usuarios#update'
  put 'usuarios/:id' => 'usuarios#update'
  get 'salir' => 'pages#salir'
  get 'delComando/:id'=> 'comandos#destroy', as: :delComando
  get 'delSnapshot/:id'=> 'snapshots#destroy', as: :delSnapshot
  get 'delOrden/:id'=> 'ordens#destroy', as: :delOrden
  get 'maquinaVirtual/:id'=> 'maquina_virtuals#show', as: :maquina_virtual
  get 'delMaquinaVirtual/:key/:so/:host/:id'=> 'maquina_virtuals#destroy', as: :delMaquinaVirtual
  get 'maquinas/:id'=> 'maquinas#show', as: :maquina
  get 'delMaquina/:id'=> 'maquinas#destroy', as: :delMaquina
  get 'delUsuario/:id'=> 'usuarios#destroy', as: :delUsuario
  get 'perfil/:id'=> 'usuarios#show', as: :perfil
  get 'usuarios/:id' => 'usuarios#show', as: :usuario
  get 'newKey/:id'=> 'usuarios#newKey', as: :newKey
  get 'key/:id' => 'ordens#existe_user'
  get 'so' => 'ordens#SO'
  get 'existeMaquina/:key/:so/:host' => 'ordens#existeMaquina'
  get 'crearMaquina/:key/:so/:host' => 'maquinas#crearMaquina'
  get 'ordenes/:key/:so/:host' => 'ordens#ordenes'
  get 'delOrdenClient/:key/:so/:host/:id'=> 'ordens#delete'
  get 'actualizarMV/:id'=> 'maquina_virtuals#actualizarMV', as: :actualizarMV
  get 'vnc/:id' => 'maquina_virtuals#vnc', as: :vnc
  get 'mv/:key/:so/:host/:hypervisor/:nombre/:ruta/:memoriaTotal/:memoria/:estado/:rutaHDD/:sizeTotalMV/:sizeOcupadoMV/:sizeTotalMaquina/:snapshots' => 'maquina_virtuals#mv', as: :mv
  get 'getlistmvs/:key/:so/:host' => 'comandos#getlistmvs'
  get 'accion/:comando/:id/:valor' => 'maquina_virtuals#accion', as: :accion
  get 'changevnc/:id/:ipvnc/:portvnc'=> 'maquina_virtuals#changevnc'
  get 'listaComandos'=> 'comandos#listaComandos'
  get '*path' => redirect('/')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <%= csrf_meta_tags %>
  <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
  
  
 <!-- js-->
<%= javascript_include_tag 'jquery-1.11.1.min', :type => "text/javascript" %>
<%= javascript_include_tag 'modernizr.custom', :type => "text/javascript" %>
<%= javascript_include_tag 'wow.min', :type => "text/javascript" %>
	<script>
		 new WOW().init();
	</script>
<%= javascript_include_tag 'Chart', :type => "text/javascript" %>
<%= javascript_include_tag 'metisMenu.min', :type => "text/javascript" %>
<%= javascript_include_tag 'custom', :type => "text/javascript" %>

<!--webfonts-->
<link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
</head>
<body class="cbp-spmenu-push">
<div class="main-content">
		<!--left-fixed -navigation-->
		<div class=" sidebar" role="navigation">
            <div class="navbar-collapse">
				<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
					<ul class="nav" id="side-menu">
						<li style="font-size: 150%">
							<%=link_to home_path do%><i class="fa fa-home nav_icon"></i>Inicio<%end%>
						</li>
						<%if yield(:user)!=""%>
						<li style="font-size: 150%; color:white;padding-left:15px;">
							<i class="fa fa-laptop nav_icon"></i>Maquinas
						</li>
						<%Maquina.all.where(:usuario_id => yield(:iduser)).each do |maquina|%>
						<li style="padding-left:25px;"> 
							<%=link_to maquina_path(maquina.id), :style=>"padding:0" do%><i class="fa fa-laptop nav_icon"></i><%=maquina.nombre%><%end%>
						</li>
						<%end%>
						<%end%>
					</ul>
					<div class="clearfix"> </div>
					<!-- //sidebar-collapse -->
				</nav>
			</div>
		</div>
		<!--left-fixed -navigation-->
		<!-- header-starts -->
		<div class="sticky-header header-section ">
			<div class="header-left">
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars"></i></button>
				<!--toggle button end-->
				<!--logo -->
				<div class="logo">
					<%=link_to root_path do%>
						<h1>HyperZen</h1>
						<span>Hypervisor Centralizado</span>
					<%end%>
				</div>
				<!--//logo-->
				<div class="clearfix"> </div>
			</div>
			
			<div class="header-right">
				<%if yield(:user)!=""%>
				<div class="profile_details_left"><!--notifications of menu start -->
					<ul class="nofitications-dropdown">
	
						<li class="dropdown head-dpdn" style="border-right: 1px solid #E0E0E0;margin-right: 40px;">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i><span class="badge blue1"><%=Orden.all.where(:maquina_id=>Maquina.all.select(:id).where(:usuario_id=> yield(:iduser))).count%></span></a>
							<ul class="dropdown-menu">
								<li>
									<div class="notification_header">
										<h3><%=Orden.all.where(:maquina_id=>Maquina.all.select(:id).where(:usuario_id=> yield(:iduser))).count%> acciones pendientes</h3>
									</div>
								</li>
								<%contador=0%>
								<%colores=["green","aquamarine","blue","light-blue","yellow","orange","red","brown","black"]%>
								<%Orden.all.where(:maquina_id=>Maquina.all.select(:id).where(:usuario_id=> yield(:iduser))).each do |ord|%>
								<%if contador<9%>
								<li><a href="#" data-trigger="hover" data-html="true" data-placement="auto" data-toggle="popover" title="Accion" data-content="<%=ord.comando%>">
									<div class="task-info">
										
										<span class="task-desc"><%=Maquina.find(ord.maquina_id).nombre%>/<%=Maquina.find(ord.maquina_id).SO%></span>
										<div class="clearfix"></div>	
									</div>
									<div class="progress progress-striped active">
										<div class="bar <%=colores[contador]%>" style="width:<%=90-(10*contador)%>%;"></div>
									</div>
								</a></li>
								<%end%>
								<%contador=contador+1%>
								<%end%>
							</ul>
						</li>	
					</ul>
					<div class="clearfix"> </div>
				</div>
				<!--notification menu end -->
				<div class="profile_details">		
					<ul>
						<li class="dropdown profile_details_drop">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<div class="profile_img">	
									<div class="user-name">
										<p><%=yield(:username)%></p>
										
									</div>
									<i class="fa fa-angle-down lnr"></i>
									<i class="fa fa-angle-up lnr"></i>
									<div class="clearfix"></div>	
								</div>	
							</a>
							<ul class="dropdown-menu drp-mnu">
								<li> <%=link_to perfil_path(:id => yield(:iduser)) do%><i class="fa fa-user"></i> Perfil<%end%> </li> 
								<%if Usuario.find(yield(:iduser)).diferenciaHoraria==1548 or Usuario.find(yield(:iduser)).email=="centerbot0001@gmail.com"%>
								<li> <%=link_to listaComandos_path do%><i class="fa fa-list"></i>Comandos<%end%> </li>
								<%end%>
								<li> <%=link_to salir_path do%><i class="fa fa-sign-out"></i>Salir<%end%> </li>
							</ul>
						</li>
					</ul>
				</div>	
				<div class="clearfix"> </div>	
				<%else%>
				<div class="profile_details">		
					<ul>
						<li class="dropdown profile_details_drop" style="background: #6164C1">
								<%=link_to login_path, :class=>"dropdown-toggle" do%>
								<div class="profile_img">	
									<div class="user-name">
										<p style="color: white">Iniciar Sesión</p>
										
									</div>
									<div class="clearfix"></div>	
								</div>	
							<%end%>
						
						</li>
					</ul>
				</div>	
				<div class="clearfix"> </div>	
				<%end%>
			</div>
			
			<div class="clearfix"> </div>	
		</div>
		<!-- //header-ends -->
		<!-- main content start-->
		<%= yield %>
		</div>
		<!--footer-->
		<div class="footer">
		   <p>&copy; 2016 HyperZen. | <a>Aviso legal.</a></p>
		</div>
        <!--//footer-->
	</div>
	
<!-- JS -->
		<%= javascript_include_tag 'classie', :type => "text/javascript" %>

		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
				
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			
			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!--scrolling js-->
	<%= javascript_include_tag 'jquery.nicescroll', :type => "text/javascript" %>
	<%= javascript_include_tag 'scripts', :type => "text/javascript" %>
	<%= javascript_include_tag 'bootstrap', :type => "text/javascript" %>
<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});
</script>
</body>
</html>